app:
   name: spring-boot-config-application-GIT REPO
   message: Hello From the Spring Boot Application ${app.name}
list:
    values: One, Two, Three
db.connection:
             connectionName: http://localhost:8090/GIT_REPO
             username: GIT
             passowrd: pattnaik
             port: 7001

management.endpoints.web.exposure.include: "*"
spring:
  profiles:
    active: testForGIT
